version: '3'

services:
  db:
    image: postgres:12.0-alpine
    container_name: ror_postgresql
    hostname: ror_postgresql
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  pg_admin:
    image: dpage/pgadmin4:4.13
    container_name: ror_pg_admin
    hostname: ror_pg_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 83:80
    depends_on:
      - db

  redis:
    image: redis:alpine3.10
    container_name: ror_redis

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ror_web
    container_name: ror_web
    volumes:
      - ${WEB_HOST_DIRECTORY}:${WEB_IMAGE_DIRECTORY}
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    tty: true
