# Config for database connection
env:
  db_username: db_username
  db_password: db_password

  # For sending email
  email_host: email_host
  email_domain: email_domain
  email_username: email_username
  email_password: email_password
  email_port: email_port
  protocol: protocol
  email_queue_name: email_queue_name

  # For backend queue
  queue_name_prefix: queue_name_prefix

  # For OAuth
  google_client_id: google_client_id
  google_client_secret: google_client_secret

  facebook_client_id: facebook_client_id
  facebook_client_secret: facebook_client_secret
