default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: app_user
  # password: app_password
  username: <%= Rails.application.credentials.env[:db_username] %>
  password: <%= Rails.application.credentials.env[:db_password] %>

development:
  <<: *default
  database: social_network_ror_development

test:
  <<: *default
  database: social_network_ror_test

production:
  <<: *default
  database: social_network_ror_production
  username: social_network_ror
  password: <%= ENV['SOCIAL_NETWORK_ROR_DATABASE_PASSWORD'] %>
